steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "$(node_version)"
    displayName: "Install Node.js"

  - script: yarn install --frozen-lockfile
    displayName: "Install dependencies"

  - script: yarn check-deps
    displayName: "Check dependencies"

  - script: yarn lint
    displayName: "Lint code"

  - script: yarn lint-docs
    displayName: "Lint docs"
