steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version_for_build)
    displayName: "Install Node.js v$(node_version_for_build)"

  - script: yarn install --frozen-lockfile
    displayName: "Install dependencies"

  - script: yarn build
    displayName: "Build dist"

  - task: NodeTool@0
    inputs:
      versionSpec: "$(node_version)"
    displayName: "Install Node.js v$(node_version)"
    condition:
      ne(variables['node_version'], variables['node_version_for_build'])

  - script: yarn test:dist
    displayName: "Run tests on dist"

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: "**/junit.xml"
    condition: and(eq(variables['REPORT_SUMMARIES'], true), succeededOrFailed())
